language: cpp
matrix:
  include:
  - os: linux
    env: PYTHON=3.5
  - os: osx
    env: PYTHON=3.6
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - deadsnakes
    - kubuntu-backports
    packages:
    - g++-4.8
    - python3.5
    - python3.5-dev
    - cmake
before_install:
- |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX=g++-4.8 CC=gcc-4.8; fi
  if [ -n "$PYTHON" ]; then
    if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "${PYTHON:0:1}" = "3" ]; then
      brew update; brew upgrade python; 
    fi
    pip3 install --user --upgrade pip virtualenv
    virtualenv -p python$PYTHON venv
    source venv/bin/activate
  fi
install:
- |
  if [ -n "$PYTHON" ]; then
    python3 setup.py sdist
    pip3 install --verbose dist/*.tar.gz
  fi
script:
- python3 setup.py test